owner: tictactrip
repo: upptime

# Add your sites here
sites:
  - name: Website
    url: https://www.tictactrip.eu
  - name: Blog
    url: https://www.tictactrip.eu/blog
  - name: API
    url: https://api.tictactrip.eu

assignees:
  - rimiti
